spring.application.name=backend-dacn

# ===============================
# CẤU HÌNH KẾT NỐI DATABASE MYSQL
# ===============================
# Sửa 'dacn_db' thành tên database bạn đã tạo trong MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dacn_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Điền username và mật khẩu MySQL của máy bạn (Thường username là rôt)
spring.datasource.username=root
spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CẤU HÌNH JPA / HIBERNATE
# ===============================
# 'update': Tự động tạo bảng (table) hoặc thêm cột mới nếu DB chưa có
spring.jpa.hibernate.ddl-auto=update

# Bật hiển thị câu lệnh SQL trên console để dễ Debug
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CẤU HÌNH BẢO MẬT JWT
# ===============================
# Đã được mã hoá Base64 sao cho vượt mốc 256bits theo chuẩn an toàn
app.jwt-secret=Q2h1b2lTZWNyZXRTaWV1QmFvTWF0Q2hvRHVBbkRBQ05DdWFUaWVuQW5oMTIzNDU2Nzg5
# Thời gian sống của Token: 7 ngày (tính bằng milliseconds)
app.jwt-expiration-milliseconds=604800000

# ===============================
# HIỂN THỊ LỖI ĐỂ TÌM BUG SWAGGER 500
# ===============================
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true

# ===============================
# CẤU HÌNH SWAGGER / OPENAPI 3
# ===============================
open.api.title=Sport E-commerce
open.api.description=Document for Sport E-commerce API
open.api.version=1.0.0
open.api.server.url=http://localhost:8080
open.api.server.description=Local (Dev)